Remove deprecated code, old files and use virtualenv
astropy/astropy-benchmarks pull request #111
Opened 2024-01-16 10:28 UTC by MridulS

This PR cleans up this repository to make it work with the main branch of astropy. This PR does a bunch of things:

- Remove old files like travis config, parsetab, logs. There is still a cron file which I am not sure if it needs to be there?
- Remove old deprecated API usage.
- Run the repo through ruff to format the python code.
- Use virtualenv to setup envs for running benchmarks.

This PR is required to make https://github.com/astropy/astropy/pull/15779 work.

2024-01-16 21:56 UTC, pllim commented
Since @zacharyburnett and @jhunkeler maintaining the version that STScI is running, maybe would be nice for one of them to take this for a spin first. Otherwise, I welcome the clean-up!

p.s. Though the black stuff makes the diff hard to read.

2024-01-16 21:56 UTC, pllim approved these changes

2024-01-16 21:57 UTC, pllim commented
@MridulS , if none of them respond, please ping me again (say, next week) and I can just YOLO-merge this. Thanks!

2024-01-17 14:27 UTC, zacharyburnett commented on asv.conf.json
> +  "environment_type": "virtualenv"
`environment.yml` could be moved to the root directory, and be whittled down to
```yaml
channels:
  - conda-forge
  - defaults

dependencies:
  - build
  - Cython
  - packaging
  - matplotlib
  - scipy
```

2024-01-17 14:31 UTC, zacharyburnett requested changes
this looks good, but I think should use `mamba` instead of `virtualenv`

2024-01-17 16:58 UTC, MridulS commented on asv.conf.json
> +  "environment_type": "virtualenv"
Thanks for the review, interestingly conda was breaking with the latest asv on my local machine with this setup. All the packages here should have wheels available so we wouldn't really need to worry about building them.

I'll have a look again if I can make this work with conda :)

2024-01-17 16:59 UTC, MridulS commented
Also are you using the https://github.com/astropy/astropy-benchmarks/blob/main/cron.sh file anywhere in your pipelines?

2024-01-22 17:07 UTC, zacharyburnett commented
> Also are you using the https://github.com/astropy/astropy-benchmarks/blob/main/cron.sh file anywhere in your pipelines?

no, I don't think anything is using that

2024-01-22 17:42 UTC, zacharyburnett approved these changes

2024-01-22 17:42 UTC, zacharyburnett commented on asv.conf.json
> +  "environment_type": "virtualenv"
Ok, that sounds good to me

2024-01-22 19:55 UTC, merged